categories = [
  {"name": "БГ Футбол", "id": 1},
  {"name": "Футбол Свят", "id": 2},
  {"name": "Баскетбол", "id": 3},
  {"name": "Моторни", "id": 4},
  {"name": "Още спорт", "id": 5},
  {"name": "Домът на футбола", "id": 10, "cat_id": 1, "payload": { "main_tag_id": 77697, "acc_tag_id": 100559, "accent_type": 7, "player_id": 1} },
  {"name": "Преди кръга", "id": 11, "cat_id": 1, "payload": { "main_tag_id": 98899, "acc_tag_id": 100560, "accent_type": 7, "player_id": 2} },
  {"name": "Героите на кръга", "id": 12, "cat_id": 1, "payload": { "main_tag_id": 98874, "acc_tag_id": 100561, "accent_type": 7, "player_id": 3} },
  {"name": "Головете на кръга", "id": 13, "cat_id": 1, "payload": { "main_tag_id": 100590, "acc_tag_id": 0, "accent_type": 7, "player_id": 4} },
  {"name": "Обзор на кръга: Ефбет Лига", "id": 14, "cat_id": 1, "payload": { "main_tag_id": 100592, "acc_tag_id": 0, "accent_type": 7, "player_id": 5} },
  {"name": "Обзор на кръга: Втора Лига", "id": 15, "cat_id": 1, "payload": { "main_tag_id": 100594, "acc_tag_id": 0, "accent_type": 7, "player_id": 6} },
  {"name": "Премиер Лийг токшоу", "id": 16, "cat_id": 2, "payload": { "main_tag_id": 100291, "acc_tag_id": 100602, "accent_type": 7, "player_id": 9} },
  {"name": "Преди кръга във Висшата лига", "id": 17, "cat_id": 2, "payload": { "main_tag_id": 100598, "acc_tag_id": 0, "accent_type": 7, "player_id": 7} },
  {"name": "Истории от Висшата лига", "id": 18, "player_id": 11, "cat_id": 2, "payload": { "main_tag_id": 100392, "acc_tag_id": 0, "accent_type": 7, "player_id": 11} },
  {"name": "Голямото интервю", "id": 19, "player_id": 12, "cat_id": 2, "payload": { "main_tag_id": 100606, "acc_tag_id": 0, "accent_type": 7, "player_id": 12} },
  {"name": "Да скъсаш мрежата", "id": 20, "player_id": 10, "cat_id": 2, "payload": { "main_tag_id": 100292, "acc_tag_id": 100604, "accent_type": 7, "player_id": 10} },
  {"name": "Обзор на кръга във Висшата лига", "id": 21, "cat_id": 2, "payload": { "main_tag_id": 100600, "acc_tag_id": 0, "accent_type": 7, "player_id": 8} },
  {"name": "Бундеслига токшоу", "id": 22, "player_id": 16, "cat_id": 2, "payload": { "main_tag_id": 100501, "acc_tag_id": 100612, "accent_type": 7, "player_id": 16} },
  {"name": "Седмично в Бундеслигата", "id": 23, "player_id": 13, "cat_id": 2, "payload": { "main_tag_id": 100609, "acc_tag_id": 0, "accent_type": 7, "player_id": 13} },
  {"name": "Обзор на кръга в Бундеслигата", "id": 24, "player_id": 14, "cat_id": 2, "payload": { "main_tag_id": 100610, "acc_tag_id": 0, "accent_type": 7, "player_id": 14} },
  {"name": "Обзор на кръга във Втора Бундеслига", "id": 25, "player_id": 15, "cat_id": 2, "payload": { "main_tag_id": 100611, "acc_tag_id": 0, "accent_type": 7, "player_id": 15} },
  {"name": "Преди кръга в Лига 1", "id": 26, "player_id": 17, "cat_id": 2, "payload": { "main_tag_id": 100613, "acc_tag_id": 0, "accent_type": 7, "player_id": 17} },
  {"name": "Обзор на кръга в Лига 1", "id": 27, "player_id": 18, "cat_id": 2, "payload": { "main_tag_id": 100614, "acc_tag_id": 0, "accent_type": 7, "player_id": 18} },
  {"name": "НБА Екшън", "id": 28, "player_id": 22, "cat_id": 3, "payload": { "main_tag_id": 100619, "acc_tag_id": 100617, "accent_type": 7, "player_id": 22} },
  {"name": "Пета четвърт", "id": 29, "player_id": 23, "cat_id": 3, "payload": { "main_tag_id": 100294, "acc_tag_id": 0, "accent_type": 7, "player_id": 23} },
  {"name": "Формула 1 Токшоу", "id": 30, "player_id": 19, "cat_id": 4, "payload": { "main_tag_id": 98900, "acc_tag_id": 0, "accent_type": 7, "player_id": 19} },
  {"name": "Обзор на Формула 1", "id": 31, "player_id": 20, "cat_id": 4, "payload": { "main_tag_id": 100616, "acc_tag_id": 0, "accent_type": 7, "player_id": 20} },
  {"name": "Формула 1 Екстра", "id": 32, "player_id": 21, "cat_id": 4, "payload": { "main_tag_id": 98901, "acc_tag_id": 0, "accent_type": 7, "player_id": 21} },
  {"name": "Спортни новини на Нова", "id": 33, "player_id": 24, "cat_id": 5, "payload": { "main_tag_id": 100620, "acc_tag_id": 0, "accent_type": 7, "player_id": 24} }
]