#  -*- coding:  utf-8 -*-
"""# Viki
# Base structure by 2018 MrKrabat
# Adapted for Viki by Arias800
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>."""
def convert_lang(sublang):
    """Convert Kodi label to country code"""
    return {
        "0": "en",
        "1": "bg",
        "2": "es",
        "3": "fr",
        "4": "pt",
        "5": "ja",
        "6": "zh",  # lang = 'zh-cn'
        "7": "tw",  # lang = 'zh-tw'
        "8": "ko",
        "9": "ab",
        "10": "aa",
        "11": "af",
        "12": "ak",
        "13": "am",
        "14": "ag",
        "15": "az",
        "16": "ms",
        "17": "id",
        "18": "jv",
        "19": "bn",
        "20": "bo",
        "21": "bs",
        "22": "ca",
        "23": "ch",
        "24": "ce",
        "25": "za",
        "26": "cy",
        "27": "da",
        "28": "de",
        "29": "dv",
        "30": "dz",
        "31": "et",
        "32": "eo",
        "33": "eu",
        "34": "to",
        "35": "ga",
        "36": "sm",
        "37": "gl",
        "38": "gd",
        "39": "hm",
        "40": "hr",
        "41": "ia",
        "42": "it",
        "43": "mu",
        "44": "cb",
        "45": "kw",
        "46": "km",
        "47": "rn",
        "48": "sw",
        "49": "hat",
        "50": "ku",
        "51": "lo",
        "52": "la",
        "53": "lv",
        "54": "lt",
        "55": "hu",
        "56": "mg",
        "57": "ml",
        "58": "mo",
        "59": "my",
        "60": "fj",
        "61": "nl",
        "62": "cr",
        "63": "no",
        "64": "or",
        "65": "uz",
        "66": "pl",
        "67": "ro",
        "68": "rm",
        "69": "st",
        "70": "sq",
        "71": "sk",
        "72": "sl",
        "73": "so",
        "74": "sh",
        "75": "fi",
        "76": "sv",
        "77": "tl",
        "78": "tt",
        "79": "vi",
        "80": "tw",
        "81": "tr",
        "82": "wo",
        "83": "yo",
        "84": "sn",
        "85": "lol",
        "86": "tm",
        "87": "is",
        "88": "cs",
        "89": "el",
        "90": "ba",
        "91": "mk",
        "92": "mn",
        "93": "ru",
        "94": "sr",
        "95": "uk",
        "96": "mne",
        "97": "kk",
        "98": "hy",
        "99": "he",
        "100": "ar",
        "101": "ur",
        "102": "skr",
        "103": "fa",
        "104": "hne",
        "105": "ne",
        "106": "mr",
        "107": "sa",
        "108": "hi",
        "109": "pa",
        "110": "gu",
        "111": "ta",
        "112": "te",
        "113": "kn",
        "114": "th",
        "115": "yue",
    }[sublang]
